spring.datasource.url=jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.data-username=sa
spring.datasource.data-password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

server.port=0

eureka.instance.instance-id=Customer-BS:${spring.application.instance-id:${random.value}}
eureka.client.healthcheck.enabled=true
spring.application.name=customer-bs

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernare.format_sql=true
spring.jpa.properties.hibernare.generate_statistics=false

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.path=/home/amanvw/Documents/AmanProjects/ShopifyWorkspace/logs/customer-bs
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR