DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(250) NOT NULL,
MIDDLE_NAME VARCHAR(250),
LAST_NAME VARCHAR(250) NOT NULL,
GENDER VARCHAR(250) NOT NULL,
CONTACT_NO VARCHAR(10) NOT NULL,
EMAIL VARCHAR(250)
);

CREATE TABLE ADDRESSES(
ADDRESS_ID INT AUTO_INCREMENT PRIMARY KEY,
ADDRESS_TYPE VARCHAR(250) NOT NULL,
ADDR_LINE_1 VARCHAR(250),
ADDR_LINE_2 VARCHAR(250),
ADDR_LINE_3 VARCHAR(250),
LANDMARK VARCHAR(250),
CITY VARCHAR(250) NOT NULL,
DISTRICT VARCHAR(250) NOT NULL,
STATE VARCHAR(250) NOT NULL,
PINCODE VARCHAR(250) NOT NULL,
CUSTOMER_ID INT,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);


INSERT INTO CUSTOMERS(FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, CONTACT_NO, EMAIL) VALUES ('Aman', 'Vijay', 'Walke', 'Male', '9876543210', 'aman@walke.com');